server:
  port: 8082
spring:
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      missing-topics-fatal: false
  datasource:
    url: jdbc:oracle:thin:@//192.168.3.206:1521/DBSONEDE
    username: grh_bea
    password: GRH_BEA  
    driver-class-name: oracle.jdbc.OracleDriver 
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

producer:
  kafka:
    topic-name: notifff

   